/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AliasPayRequestAmounts } from './aliasPayRequestAmounts';


export interface AliasPayRequest {
    /**
     * Alias to pay from
     */
    aliasfrom: string;
    amounts: AliasPayRequestAmounts;
    /**
     * Set to true to use InstantSend to send this transaction or false otherwise.
     */
    instantsend?: boolean;
    /**
     * An addresses array to subtract fee from them.
     */
    subtractfeefromamount?: Array<string>;
}
