/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface EscrowListEntry {
    escrow?: string;

    time?: number;

    seller?: string;

    arbiter?: string;

    buyer?: string;

    offer?: string;

    offertitle?: string;

    offeracceptlink?: string;

    total?: number;

    status?: string;

    expired?: boolean;

}
