/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Escrow {
    _id?: string;
    time?: number;
    seller?: string;
    arbiter?: string;
    buyer?: string;
    witness?: string;
    offer?: string;
    offer_price?: number;
    offer_title?: string;
    reseller?: string;
    quantity?: number;
    total_with_fee?: number;
    total_without_fee?: number;
    bid_in_offer_currency_per_unit?: number;
    total_or_bid_in_payment_option_per_unit?: number;
    buynow?: boolean;
    commission?: number;
    arbiterfee?: number;
    networkfee?: number;
    witnessfee?: number;
    shipping?: number;
    deposit?: number;
    currency?: string;
    exttxid?: string;
    escrowaddress?: string;
    paymentoption?: string;
    redeem_txid?: string;
    redeem_script?: string;
    txid?: string;
    height?: number;
    role?: number;
    expired?: boolean;
    acknowledged?: boolean;
    status?: number;
}
