/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface OfferAccept {
    offer?: string;

    title?: string;

    id?: string;

    btctxid?: string;

    alias?: string;

    buyer?: string;

    height?: number;

    quantity?: number;

    currency?: string;

    linkofferaccept?: string;

    offer_discount_percentage?: number;

    escrowlink?: string;

    systotal?: number;

    price?: number;

    total?: number;

    ismine?: boolean;

    status?: string;

    pay_message?: string;

    time?: string;

}
