/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface StoreDataRequest {
    /**
     * Identifier for existing data to update.
     */
    existingDataId?: string;

    /**
     * The type of data being stored, ie: 'aliasdata'.
     */
    dataType: string;

    /**
     * The data to be stored on the decentralized storage facility. Max size 500kb.
     */
    data: string;

    /**
     * Array of data warehousing facilities to use to store the data, valid values: BFAZURE.
     */
    storeLocations?: Array<string>;

}
