export * from './aliases.service';
import { AliasesService } from './aliases.service';
export * from './blockmarket.service';
import { BlockmarketService } from './blockmarket.service';
export * from './certificates.service';
import { CertificatesService } from './certificates.service';
export * from './escrow.service';
import { EscrowService } from './escrow.service';
export * from './general.service';
import { GeneralService } from './general.service';
export * from './messaging.service';
import { MessagingService } from './messaging.service';
export * from './offers.service';
import { OffersService } from './offers.service';
export const APIS = [AliasesService, BlockmarketService, CertificatesService, EscrowService, GeneralService, MessagingService, OffersService];
