/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {
  Headers,
  Http,
  RequestMethod,
  RequestOptions,
  RequestOptionsArgs,
  Response,
  URLSearchParams
} from '@angular/http';
import {CustomQueryEncoderHelper} from '../encoder';

import {Observable} from 'rxjs/Observable';
import '../rxjs-operators';
import {LoginResponse} from '../model/loginResponse';

import {BASE_PATH} from '../variables';
import {Configuration} from '../configuration';


@Injectable()
export class BlockmarketService {

    protected basePath = 'http://localhost:8001';
  public defaultHeaders = new Headers();
  public configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
          this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }

    /**
     * Returns a session token for use with subsquent protected calls.
     * @param auth SHA1 hash of the user&#39;s authentication information- usernamepassword.
     */
    public login(auth: string, extraHttpRequestParams?: RequestOptionsArgs): Observable<LoginResponse> {
        return this.loginWithHttpInfo(auth, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     *
     * Returns a session token for use with subsquent protected calls.
     * @param auth SHA1 hash of the user&#39;s authentication information- usernamepassword.

     */
    public loginWithHttpInfo(auth: string, extraHttpRequestParams?: RequestOptionsArgs): Observable<Response> {
        if (auth === null || auth === undefined) {
            throw new Error('Required parameter auth was null or undefined when calling login.');
        }

      let queryParameters = new URLSearchParams('', new CustomQueryEncoderHelper());
        if (auth !== undefined) {
            queryParameters.set('auth', <any>auth);
        }

      let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845

        // to determine the Accept header
      let httpHeaderAccepts: string[] = [
            'application/json'
        ];
      let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
      if (httpHeaderAcceptSelected != undefined) {
        headers.set("Accept", httpHeaderAcceptSelected);
      }

      // to determine the Content-Type header
      let consumes: string[] = [
        'application/json'
      ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

      return this.http.request(`${this.basePath}/login`, requestOptions);
    }

}
